/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.whaley.launcher;

public final class R {
  public static final class color {
    public static final int accent_color=0x7f010000;
    public static final int bg_color=0x7f010001;
    public static final int card_border_default=0x7f010002;
    public static final int card_border_focused=0x7f010003;
    public static final int card_default_bg=0x7f010004;
    public static final int card_focused_bg=0x7f010005;
    public static final int star_color=0x7f010006;
    public static final int text_main=0x7f010007;
    public static final int text_sub=0x7f010008;
  }
  public static final class drawable {
    public static final int app_icon=0x7f020000;
    public static final int app_icon_focused=0x7f020001;
    public static final int app_icon_normal=0x7f020002;
    public static final int app_item_selector=0x7f020003;
    public static final int card_focused=0x7f020004;
    public static final int card_normal=0x7f020005;
    public static final int card_selector=0x7f020006;
    public static final int premium_bg=0x7f020007;
    public static final int wifi_offline=0x7f020008;
    public static final int wifi_online=0x7f020009;
  }
  public static final class id {
    public static final int apps_container=0x7f030000;
    public static final int apps_grid=0x7f030001;
    public static final int card_av=0x7f030002;
    public static final int card_hdmi1=0x7f030003;
    public static final int card_hdmi2=0x7f030004;
    public static final int card_settings=0x7f030005;
    public static final int countdown_container=0x7f030006;
    public static final int iv_wifi_status=0x7f030007;
    public static final int progress_bar=0x7f030008;
    public static final int star_av=0x7f030009;
    public static final int star_hdmi1=0x7f03000a;
    public static final int star_hdmi2=0x7f03000b;
    public static final int tv_countdown=0x7f03000c;
  }
  public static final class layout {
    public static final int activity_main=0x7f040000;
    public static final int dialog_all_apps=0x7f040001;
  }
  public static final class string {
    public static final int app_name=0x7f050000;
    public static final int av=0x7f050001;
    public static final int countdown_cancelled=0x7f050002;
    public static final int countdown_template=0x7f050003;
    public static final int hdmi1=0x7f050004;
    public static final int hdmi2=0x7f050005;
    public static final int settings=0x7f050006;
  }
  public static final class style {
    public static final int Theme_Launcher=0x7f060000;
  }
}